http://datakorea.datastore.or.kr/profile/geo/gyeonggi-do/

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import folium
import platform

from matplotlib import font_manager, rc
%matplotlib inline

## 운영체제별 글꼴 세팅

path = "c:/Windows/Fonts/malgun.ttf"
if platform.system() == 'Darwin':
    font_name = 'Apple SD Gothic Neo'
    rc('font', family='Apple SD Gothic Neo')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    font_name = font_manager.FontProperties(fname="/usr/share/fonts/nanumfont/NanumGothic.ttf")
    rc('font', family="NanumGothic")

In [3]:
data=pd.read_csv("data_1/행정구역_시군구_별__성별_인구수_20210621174937.csv")
data

     행정구역(시군구)별    2021. 05 2021. 05.1 2021. 05.2
0    행정구역(시군구)별    총인구수 (명)  남자인구수 (명)  여자인구수 (명)
1           경기도  13,488,910  6,789,327  6,699,583
2        　　　수원시   1,184,922    596,759    588,163
3        　　　고양시   1,080,656    529,030    551,626
4        　　　용인시   1,077,701    534,842    542,859
5        　　　성남시     931,626    461,504    470,122
6        　　　화성시     867,819    450,855    416,964
7        　　　부천시     811,225    402,337    408,888
8       　　　남양주시     723,215    360,076    363,139
9        　　　안산시     655,555    336,303    319,252
10       　　　안양시     550,750    272,348    278,402
11       　　　평택시     548,131    284,559    263,572
12       　　　시흥시     510,833    266,839    243,994
13       　　　김포시     482,578    241,645    240,933
14       　　　덕양구     480,156    237,211    242,945
15       　　　분당구     478,685    232,148    246,537
16       　　　파주시     471,219    238,960    232,259
17      　　　의정부시     460,923    227,073    233,850
18       　　　기흥구     439,953    217,184    222,769
19       　　　광주시     384,306    196,393    187,913
20       　　　수지구     377,350    183,897    193,453
21       　　　영통구     365,887    183,467    182,420
22       　　　권선구     365,384    184,566    180,818
23       　　　상록구     353,575    180,419    173,156
24       　　　동안구     312,419    153,034    159,385
25       　　　하남시     302,681    151,874    150,807
26       　　　단원구     301,980    155,884    146,096
27      　　　일산동구     300,437    146,195    154,242
28      　　　일산서구     300,063    145,624    154,439
29       　　　광명시     295,742    145,900    149,842
30       　　　장안구     270,807    136,498    134,309
31       　　　군포시     270,754    134,288    136,466
32       　　　처인구     260,398    133,761    126,637
33       　　　만안구     238,331    119,314    119,017
34       　　　수정구     237,729    120,292    117,437
35       　　　양주시     235,276    119,349    115,927
36       　　　오산시     230,702    119,532    111,170
37       　　　이천시     219,591    113,745    105,846
38       　　　중원구     215,212    109,064    106,148
39       　　　구리시     194,838     96,640     98,198
40       　　　안성시     188,704     97,419     91,285
41       　　　팔달구     182,844     92,228     90,616
42       　　　의왕시     162,239     80,710     81,529
43       　　　포천시     147,425     78,138     69,287
44       　　　양평군     119,826     60,147     59,679
45       　　　여주시     111,939     56,898     55,041
46      　　　동두천시      93,292     46,606     46,686
47       　　　과천시      69,027     33,887     35,140
48       　　　가평군      62,344     32,125     30,219
49       　　　연천군      43,071     22,546     20,525
50     　　　송탄출장소           0          0          0
51     　　　안중출장소           0          0          0
52     　　　풍양출장소           0          0          0
53  　　　화성시동부출장소           0          0          0
54  　　　화성시동탄출장소           0          0          0

In [5]:
top_5=data[2:14]
top_5.reset_index(inplace=True)
top_5

    index 행정구역(시군구)별   2021. 05 2021. 05.1 2021. 05.2
0       2     　　　수원시  1,184,922    596,759    588,163
1       3     　　　고양시  1,080,656    529,030    551,626
2       4     　　　용인시  1,077,701    534,842    542,859
3       5     　　　성남시    931,626    461,504    470,122
4       6     　　　화성시    867,819    450,855    416,964
5       7     　　　부천시    811,225    402,337    408,888
6       8    　　　남양주시    723,215    360,076    363,139
7       9     　　　안산시    655,555    336,303    319,252
8      10     　　　안양시    550,750    272,348    278,402
9      11     　　　평택시    548,131    284,559    263,572
10     12     　　　시흥시    510,833    266,839    243,994
11     13     　　　김포시    482,578    241,645    240,933